# Generated by Django 2.2 on 2019-11-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20191108_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accType',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Saving'), (2, 'Insurance')]),
        ),
    ]
