# Generated by Django 2.2.7 on 2019-11-12 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_auto_20191111_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='accounts',
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Accounts.Customer'),
        ),
    ]
